spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Tcc
    username: Wallace
    password: P4ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true

  mvc:
    cors:
      allowed-origins: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
